// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oaemynytysnkhxmsfbnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hZW15bnl0eXNua2h4bXNmYm56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NTE1MjUsImV4cCI6MjA2OTUyNzUyNX0.KjP21-NUE7Z86lJTuUFsRa38y5gpWi9YDK77CaS7QGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});